sudo: required
language: go
services:
  - docker
before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - pip install --user docker-compose
  - docker-compose up -d
  - go get -u github.com/golang/dep/...
  - dep ensure
script:
  - go test ./...